import sys
import unittest
import tempfile
from unittest import mock
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
from decision_server import (
    REVISION,
    main,
    materialize_snapshot,
    resolve_classifier_package,
)


class AdapterTests(unittest.TestCase):
    def _snapshot(self, root: Path) -> Path:
        snapshot = root / "snapshot"
        snapshot.mkdir()
        (snapshot / "config.json").write_text("{}", encoding="utf-8")
        (snapshot / "decision_head.safetensors").write_bytes(b"weights")
        return snapshot

    def test_prepare_only_materializes_without_starting_server(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            snapshot = self._snapshot(root)
            cache = root / "cache"
            with mock.patch("decision_server._snapshot_download", return_value=snapshot), \
                    mock.patch("decision_server.HTTPServer") as server:
                self.assertEqual(main(["--prepare-only", "--cache-root", str(cache)]), 0)
            server.assert_not_called()
            self.assertTrue((cache / REVISION / "config.json").is_file())

    def test_runtime_requires_local_cache_without_downloading(self):
        with tempfile.TemporaryDirectory() as directory:
            cache = Path(directory) / "cache"
            with mock.patch("decision_server._snapshot_download", side_effect=OSError("offline")) as download:
                with self.assertRaisesRegex(RuntimeError, "not cached"):
                    resolve_classifier_package(cache)
            download.assert_called_once_with(allow_download=False)
            self.assertFalse(cache.exists())

    def test_runtime_download_requires_explicit_opt_in(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            snapshot = self._snapshot(root)
            cache = root / "cache"
            with mock.patch("decision_server._snapshot_download", return_value=snapshot) as download:
                package = resolve_classifier_package(cache, allow_download=True)
            self.assertEqual(package, cache / REVISION)
            download.assert_called_once_with(allow_download=True)

    def test_materializes_linked_snapshot_without_transients_and_reuses_cache(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            hub = root / "hub"
            model_cache = hub / "models--vllm-sr--Decision-2.0-Kai-0.6B"
            snapshot = model_cache / "snapshots" / REVISION
            blobs = model_cache / "blobs"
            shared_blobs = hub / "blobs"
            cache = root / "materialized"
            snapshot.mkdir(parents=True)
            blobs.mkdir(parents=True)
            shared_blobs.mkdir(parents=True)
            expected = {
                "config.json": b"config bytes",
                ".gitattributes": b"*.bin filter=lfs\n",
                "decision2/api.py": b"api bytes",
                "assets/banner.png": b"shared asset bytes",
                "backbone/model.safetensors": b"model bytes",
            }
            for relative, content in expected.items():
                backing_root = shared_blobs if relative == "assets/banner.png" else blobs
                backing = backing_root / relative.replace("/", "_")
                backing.parent.mkdir(parents=True, exist_ok=True)
                backing.write_bytes(content)
                link = snapshot / relative
                link.parent.mkdir(parents=True, exist_ok=True)
                link.symlink_to(backing)
            transient = snapshot / "decision2/__pycache__/api.cpython-312.pyc"
            transient.parent.mkdir(parents=True)
            transient.write_bytes(b"generated bytecode")

            target = materialize_snapshot(snapshot, cache)
            self.assertEqual(target, cache / REVISION)
            self.assertEqual(
                {relative: (target / relative).read_bytes() for relative in expected},
                expected,
            )
            self.assertFalse(any(path.is_symlink() for path in target.rglob("*")))
            self.assertFalse((target / "decision2/__pycache__").exists())

            mtime = (target / "config.json").stat().st_mtime_ns
            self.assertEqual(materialize_snapshot(snapshot, cache), target)
            self.assertEqual((target / "config.json").stat().st_mtime_ns, mtime)




if __name__ == "__main__":
    unittest.main()
